baseURL = "https://opmodel.dev/"
title = "Open Platform Model"
languageCode = "en-us"
contentDir = "content"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = true

[module]
  proxy = "direct"
  [module.hugoVersion]
    min = "0.126.0"
  # Docsy temporarily disabled due to i18n format issues
  # Will re-enable once resolved
  # [[module.imports]]
  #   path = "github.com/google/docsy"
  #   disable = false
  # [[module.imports]]
  #   path = "github.com/google/docsy/dependencies"
  #   disable = false

[params]
  copyright = "Open Platform Model Contributors"
  privacy_policy = ""
  version_menu = "Releases"
  archived_version = false
  version = "v0.1"
  url_latest_version = "https://opmodel.dev"
  github_repo = "https://github.com/open-platform-model/opmodel.dev"
  github_project_repo = "https://github.com/open-platform-model/catalog"
  github_branch = "main"
  
  [params.ui]
    sidebar_menu_compact = true
    breadcrumb_disable = false
    sidebar_search_disable = false
    navbar_logo = true
    footer_about_disable = false
    
  [params.ui.feedback]
    enable = true
    yes = 'Glad to hear it! Please <a href="https://github.com/open-platform-model/opmodel.dev/issues/new">tell us how we can improve</a>.'
    no = 'Sorry to hear that. Please <a href="https://github.com/open-platform-model/opmodel.dev/issues/new">tell us how we can improve</a>.'

  [params.links]
    [[params.links.developer]]
      name = "GitHub"
      url = "https://github.com/open-platform-model"
      icon = "fab fa-github"
      desc = "Open Platform Model on GitHub"

[build]
  [build.buildStats]
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

[languages]
  [languages.en]
    title = "Open Platform Model"
    description = "A declarative platform model for describing applications"
    languageName = "English"
    weight = 1
